server:
  port: 8100
  servlet:
    context-path: /shop-auth
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    url: jdbc:postgresql://localhost:5434/USERS
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
jwt:
  secret: dwesfedgsreghrthrfdgrtghiojfcoidjcdopiw44433c2
  lifetime: 36000000
