version: '3'

services:

  postgres1:
    image: postgres:9.6
    domainname: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=PRODUCTS
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres"]
      interval: 5s
      timeout: 1s
      retries: 2

  postgres2:
    image: postgres:9.6
    domainname: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=USERS
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres"]
      interval: 5s
      timeout: 1s
      retries: 2

  postgres3:
    image: postgres:9.6
    domainname: postgres
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=FILES
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres"]
      interval: 5s
      timeout: 1s
      retries: 2

  flyway1:
    image: boxfuse/flyway
    command: -url=jdbc:postgresql://postgres1:5432/PRODUCTS -schemas=postgres -user=postgres -password=postgres -connectRetries=30 migrate
    volumes:
      - ./flyway/core:/flyway/sql
    depends_on:
      - postgres1

  flyway2:
    image: boxfuse/flyway
    command: -url=jdbc:postgresql://postgres2:5432/USERS -schemas=postgres -user=postgres -password=postgres -connectRetries=30 migrate
    volumes:
      - ./flyway/users:/flyway/sql
    depends_on:
      - postgres2

  flyway3:
    image: boxfuse/flyway
    command: -url=jdbc:postgresql://postgres3:5432/FILES -schemas=postgres -user=postgres -password=postgres -connectRetries=30 migrate
    volumes:
      - ./flyway/filestore:/flyway/sql
    depends_on:
      - postgres3

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
