server:
  port: 8080
  servlet:
    context-path: /
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/Market
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
jwt:
  secret: dwesfedgsreghrthrfdgrtghiojfcoidjcdopiwad233c2
  lifetime: 36000000
springdoc:
  swagger-ui:
    path: /api-doc
logging:
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.boot: ERROR
    org.hibernate: ERROR
  file:
    name: logs/shop.log