server:
  port: 5555

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://127.0.0.1:3000"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://127.0.0.1:8120
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/shop-core
            - JwtAuthFilter
        - id: cart-service
          uri: http://127.0.0.1:8110
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/shop-cart
            - JwtAuthFilter
        - id: auth-service
          uri: http://127.0.0.1:8100
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/shop-auth
            - JwtAuthFilter
        - id: favorite-product-service
          uri: http://127.0.0.1:8111
          predicates:
            - Path=/favorite/**
          filters:
            - StripPrefix=1
            - PrefixPath=/shop-favorite-products
            - JwtAuthFilter
        - id: file-storage-service
          uri: http://127.0.0.1:8130
          predicates:
            - Path=/file/**
          filters:
            - StripPrefix=1
            - PrefixPath=/shop-files

jwt:
  secret: dwesfedgsreghrthrfdgrtghiojfcoidjcdopiw44433c2
