server:
  port: 8110
  servlet:
    context-path: /shop-cart
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/Market
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
integrations:
  product-service:
    url: http://127.0.0.1:8120/shop-core/
    connection-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000


