server:
  port: 8120
  servlet:
    context-path: /shop-core
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    url: jdbc:postgresql://localhost:5433/PRODUCTS
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
integrations:
  cart-service:
    url: http://127.0.0.1:8110/shop-cart/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000
  auth-service:
    url: http://127.0.0.1:8100/shop-auth/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000
